# Generated by Django 4.1.4 on 2022-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
